[package]
name = "tahuc_semantic"
version = "0.1.0"
edition = "2024"

[dependencies]
tahuc_span = { path = "../tahuc_span" }
tahuc_lexer = { path = "../tahuc_lexer" }
tahuc_ast = { path = "../tahuc_ast" }
tahuc_diagnostics = { path = "../tahuc_diagnostics" }