[workspace]
resolver = "2"
members = [
    "compiler/tahuc",
]

[workspace.package]
authors = ["lutfisobri <lutfisobri@gmail.com>"]
version = "0.1.0"
edition = "2024"
readme = "README.md"
repository = "https://github.com/tahu-lang/tahu"