[package]
name = "tahuc_codegen_llvm"
version = "0.1.0"
edition = "2024"

[dependencies]
tahuc_span = { path = "../tahuc_span" }
tahuc_ast = { path = "../tahuc_ast" }
tahuc_hir = { path = "../tahuc_hir" }
tahuc_mir = { path = "../tahuc_mir" }
tahuc_llvm = { path = "../tahuc_llvm" }