[package]
name = "tahuc_diagnostics"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "1.0"
atty = "0.2.14"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

tahuc_span = { path = "../tahuc_span" }